# Generated by Django 3.1.3 on 2022-05-05 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_question_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course'),
        ),
    ]
