# Generated by Django 3.1.3 on 2022-04-30 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20220429_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='maek',
            new_name='mark',
        ),
    ]
