# Generated by Django 3.1.3 on 2022-04-30 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20220429_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='choice',
        ),
    ]
