# Generated by Django 3.1.3 on 2022-05-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20220505_0149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
