# Generated by Django 3.1.3 on 2022-05-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0007_auto_20220506_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='choices',
            field=models.CharField(max_length=255),
        ),
    ]
